spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      database: rest_api
      uri: mongodb+srv://se202013:SpringBoot@cluster0.utmef.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: se202013@dsu.edu.pk
    password: zdwx gpnp deda ciij # Use App Password if 2FA is enabled
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080